<?php

namespace Flock\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlockRepository extends EntityRepository
{
    /**
     * @param $limit
     * @param $offset
     * @return array
     */
    public function getActiveFlocks($limit, $offset)
    {
        return array();
    }

    public function getActiveFlocksCount()
    {
        return 100;
    }
}
