<?php

namespace Flock\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * FlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlockRepository extends EntityRepository
{
}
