<?php

namespace Flock\MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getActiveUsersCount()
    {
        $query = $this->getEntityManager()->createQuery('SELECT COUNT(u.id) FROM '.$this->getEntityName().' u WHERE u.enabled = 1');

        return $query->getSingleScalarResult();
    }
}
